ENV['VAGRANT_NO_PARALLEL'] = 'yes'

Vagrant.configure(2) do |config|

  config.vm.provision "shell", path: "bootstrap.sh"

  config.vm.define "client" do |client|
    # client.vm.box = "generic/ubuntu2004"
    client.vm.box = "bento/ubuntu-24.04"
    client.vm.hostname = "client.example.com"
    client.vm.network "private_network", ip: "172.42.42.20"
    client.vm.provider "virtualbox" do |vb|
      vb.name = "client"
      vb.memory = 512
      vb.cpus = 1
    end
  end

  config.vm.define "elastic-server" do |server|
    server.vm.provision "shell", path: "install-docker.sh"
    config.vm.provision "file", source: "docker-compose.yml", destination: "docker-compose.yml"
    config.vm.provision "file", source: "settings", destination: "settings"

    # server.vm.box = "generic/ubuntu2004"
    server.vm.box = "bento/ubuntu-24.04"
    server.vm.hostname = "elasticstack"
    server.vm.network "private_network", ip: "172.42.42.10"
    server.vm.provider "virtualbox" do |vb|
      vb.name = "elastic-server"
      vb.memory = 4096
      vb.cpus = 1
    end
  end

end
